variable "prefix" { description = "Resource Name Prefix"}
variable "environment"         { description = "Environment name" }
variable "aws_region"          { description = "AWS region for CloudWatch logs" }
variable "app_a_id"            { description = "App Subnet A ID" }
variable "app_b_id"            { description = "App Subnet B ID" }
variable "ecs_sg_id"           { description = "ECS Security Group ID" }
variable "workload_alb_tg_arn" { description = "Workload ALB target group ARN" }
variable "container_image"     { description = "Docker image for the echoserver container" }
variable "task_cpu"            { description = "CPU units for the ECS task" }
variable "task_memory"         { description = "Memory (MB) for the ECS task" }
variable "desired_count"       { description = "Number of ECS tasks to run" }
variable "log_retention_days"  { description = "CloudWatch log retention in days" }