variable "prefix" { description = "Resource Name Prefix"}
variable "environment"                { description = "Environment name" }
variable "internet_vpc_id"            { description = "Internet VPC ID" }
variable "igw_id"                     { description = "Internet Gateway ID" }
variable "workload_vpc_cidr"          { description = "Workload VPC CIDR" }
variable "tgw_id"                     { description = "Transit Gateway ID" }
variable "internet_tgw_attachment_id" { description = "Internet TGW attachment ID" }
variable "workload_tgw_attachment_id" { description = "Workload TGW attachment ID" }
variable "gateway_a_id"               { description = "Gateway Subnet A ID" }
variable "gateway_b_id"               { description = "Gateway Subnet B ID" }
variable "nat_gateway_id"             { description = "NAT Gateway ID" }
variable "internet_tgw_id"     { description = "Internet TGW Subnet ID" }
variable "workload_vpc_id"            { description = "Workload VPC ID" }
variable "web_a_id"                   { description = "Web Subnet A ID" }
variable "web_b_id"                   { description = "Web Subnet B ID" }
variable "app_a_id"                   { description = "App Subnet A ID" }
variable "app_b_id"                   { description = "App Subnet B ID" }