variable "prefix" { description = "Resource Name Prefix" }
variable "environment" { description = "Environment name" }
variable "internet_vpc_cidr" { description = "Internet VPC CIDR" }
variable "workload_vpc_cidr" { description = "Workload VPC CIDR" }
variable "firewall_cidr" { description = "Firewall Subnet CIDR" }
variable "gateway_a_cidr" { description = "Gateway Subnet A CIDR" }
variable "gateway_b_cidr" { description = "Gateway Subnet B CIDR" }
variable "internet_tgw_cidr" { description = "Internet TGW Subnet CIDR" }
variable "web_a_cidr" { description = "Web Subnet A CIDR" }
variable "web_b_cidr" { description = "Web Subnet B CIDR" }
variable "workload_tgw_cidr" { description = "Workload TGW Subnet CIDR" }
variable "app_a_cidr" { description = "App Subnet A CIDR" }
variable "app_b_cidr" { description = "App Subnet B CIDR" }
variable "data_a_cidr" { description = "Data Subnet A CIDR" }
variable "data_b_cidr" { description = "Data Subnet B CIDR" }
variable "az_a" { description = "Primary Availability Zone" }
variable "az_b" { description = "Secondary Availability Zone" }