variable "prefix" { description = "Resource Name Prefix" }
variable "environment" { description = "Environment Name" }
variable "internet_vpc_id" { description = "Internet VPC ID" }
variable "workload_vpc_id" { description = "Workload VPC ID" }
variable "gateway_a_id" { description = "Gateway Subnet A ID" }
variable "gateway_b_id" { description = "Gateway Subnet B ID" }
variable "web_a_id" { description = "Web Subnet A ID" }
variable "web_b_id" { description = "Web Subnet B ID" }
variable "internet_alb_sg_id" { description = "Internet ALB Security Group ID" }
variable "workload_alb_sg_id" { description = "Workload ALB Security Group ID" }
variable "workload_nlb_tg_port" { description = "Workload NLB Target Group Port" }
variable "workload_nlb_lis_port" { description = "Workload NLB Listener Port" }
variable "workload_alb_tg_port" { description = "Workload ALB Target Group Port" }
variable "workload_alb_lis_port" { description = "Workload ALB Listener Port" }
variable "internet_alb_tg_port" { description = "Internet ALB Target Group Port" }
variable "internet_alb_lis_port" { description = "Internet ALB Listener Port" }